### ISSUE TITLE
Requesting information

### ISSUE THREAD

**Issue by jaybee84** [diogocamacho/druid#2]
I am planning to apply DRUID to some datasets available to Sage Bionetworks and wanted to understand the rationale of the method and underlying algorithm a bit more to make sure it is applied appropriately to the right kind of data. Would you be able to point me to any publication/poster/slide-deck with some documentation of the method? 

-Jineta Banerjee (Sage Bionetworks)

**Comment by diogocamacho** [comment]
hi jineta,

i don't have a publication with details, and the slide decks are vague, but i'm happy to email you details on the algorithm. email me directly at diogo.camacho.2008 at gmail and i'll walk you through it.

**Comment by jaybee84** [comment]
Thanks @diogocamacho, I have sent you a direct email. Please let me know if you did not receive it.
